Implement URL rewrite (also, re-indent nginx file…)
YunoHost-Apps/opensondage_ynh pull request #62
Opened 2020-04-24 14:48 UTC by Salamandar

Fixes #61

2020-10-04 18:40 UTC, ericgaspar requested changes
As we have now PHP set to 7.3 in _common.sh

2020-10-04 18:40 UTC, ericgaspar commented on conf/nginx.conf
> +        fastcgi_pass unix:/var/run/php/php7.0-fpm-__NAME__.sock;
```suggestion
        fastcgi_pass unix:/var/run/php/php__PHPVERSION__-fpm-__NAME__.sock;
```

2020-12-14 12:42 UTC, Salamandar commented
I think that's good now, the requested changes were merge before I had time to read them ^^'

2020-12-14 12:56 UTC, ericgaspar commented
package 'php7.3-fpdf' has no installation candidate...
we may need to set it as 'php-fpdf'

2020-12-14 13:12 UTC, Salamandar commented
We can do another pull request for that :D
Maybe other packages have the same issue.

2020-12-14 13:14 UTC, ericgaspar commented
This is failing the CI tests...

2020-12-14 13:17 UTC, Salamandar commented
My changes aren't related to php installation, so I don't understand.
Oh, but i'm not merging on Master but Testing ! Testing should be failing on CI too I guess.

2020-12-14 13:20 UTC, ericgaspar approved these changes

2021-07-20 16:40 UTC, merged