Various fixes
YunoHost-Apps/opensondage_ynh pull request #70
Opened 2021-03-14 21:35 UTC by yalh76

## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/opensondage_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/opensondage_ynh%20PR-NUM-%20(USERNAME)/)

2021-03-14 21:35 UTC, yalh76 commented
!testme

2021-03-15 19:09 UTC, yalh76 commented
!testme

2021-04-17 16:57 UTC, alexAubin approved these changes
LGTM

2021-04-17 16:59 UTC, alexAubin requested changes

2021-04-17 16:59 UTC, alexAubin commented on scripts/_common.sh
> +pkg_dependencies="php${YNH_PHP_VERSION}-fpdf php${YNH_PHP_VERSION}-cli php${YNH_PHP_VERSION}-xml"
Apparently tho the CI complains that : 

` E: Package 'php7.3-fpdf' has no installation candidate`

2021-04-17 17:07 UTC, yalh76 commented
!testme

2021-04-22 18:03 UTC, merged